kind: Deployment
apiVersion: apps/v1
metadata:
  name: pruebatecnica
  namespace: appgate
  labels:
    app: pruebatecnica
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pruebatecnica
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pruebatecnica
    spec:
      containers:
        - name: pruebatecnica
          image: 'nicoalca/pruebatecnica:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
